# Generated by Django 5.1.7 on 2025-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bodaboda', 'Bodaboda'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
